package com.self.base.dao;

import com.self.base.entity.UpmsUser;
import com.self.base.entity.UpmsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    long countByExample(UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int deleteByExample(UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int insert(UpmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int insertSelective(UpmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    List<UpmsUser> selectByExample(UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    UpmsUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") UpmsUser record, @Param("example") UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int updateByExample(@Param("record") UpmsUser record, @Param("example") UpmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int updateByPrimaryKeySelective(UpmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upms_user
     *
     * @mbg.generated Tue Apr 03 13:57:57 CST 2018
     */
    int updateByPrimaryKey(UpmsUser record);
}