package com.self.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntityOidIsNull() {
            addCriterion("ENTITY_OID is null");
            return (Criteria) this;
        }

        public Criteria andEntityOidIsNotNull() {
            addCriterion("ENTITY_OID is not null");
            return (Criteria) this;
        }

        public Criteria andEntityOidEqualTo(BigDecimal value) {
            addCriterion("ENTITY_OID =", value, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidNotEqualTo(BigDecimal value) {
            addCriterion("ENTITY_OID <>", value, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidGreaterThan(BigDecimal value) {
            addCriterion("ENTITY_OID >", value, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ENTITY_OID >=", value, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidLessThan(BigDecimal value) {
            addCriterion("ENTITY_OID <", value, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ENTITY_OID <=", value, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidIn(List<BigDecimal> values) {
            addCriterion("ENTITY_OID in", values, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidNotIn(List<BigDecimal> values) {
            addCriterion("ENTITY_OID not in", values, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENTITY_OID between", value1, value2, "entityOid");
            return (Criteria) this;
        }

        public Criteria andEntityOidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENTITY_OID not between", value1, value2, "entityOid");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNull() {
            addCriterion("DISPLAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNotNull() {
            addCriterion("DISPLAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameEqualTo(String value) {
            addCriterion("DISPLAY_NAME =", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotEqualTo(String value) {
            addCriterion("DISPLAY_NAME <>", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThan(String value) {
            addCriterion("DISPLAY_NAME >", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME >=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThan(String value) {
            addCriterion("DISPLAY_NAME <", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME <=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLike(String value) {
            addCriterion("DISPLAY_NAME like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotLike(String value) {
            addCriterion("DISPLAY_NAME not like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIn(List<String> values) {
            addCriterion("DISPLAY_NAME in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotIn(List<String> values) {
            addCriterion("DISPLAY_NAME not in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME not between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("GENDER =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("GENDER >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("GENDER <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("GENDER like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("GENDER not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("GENDER in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("MOBILE_NO is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("MOBILE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("MOBILE_NO =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("MOBILE_NO <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("MOBILE_NO >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("MOBILE_NO <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("MOBILE_NO like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("MOBILE_NO not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("MOBILE_NO in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("MOBILE_NO not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("MOBILE_NO between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("MOBILE_NO not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNull() {
            addCriterion("TEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andTelNoIsNotNull() {
            addCriterion("TEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTelNoEqualTo(String value) {
            addCriterion("TEL_NO =", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotEqualTo(String value) {
            addCriterion("TEL_NO <>", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThan(String value) {
            addCriterion("TEL_NO >", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_NO >=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThan(String value) {
            addCriterion("TEL_NO <", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLessThanOrEqualTo(String value) {
            addCriterion("TEL_NO <=", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoLike(String value) {
            addCriterion("TEL_NO like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotLike(String value) {
            addCriterion("TEL_NO not like", value, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoIn(List<String> values) {
            addCriterion("TEL_NO in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotIn(List<String> values) {
            addCriterion("TEL_NO not in", values, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoBetween(String value1, String value2) {
            addCriterion("TEL_NO between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andTelNoNotBetween(String value1, String value2) {
            addCriterion("TEL_NO not between", value1, value2, "telNo");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andStatusUsedIsNull() {
            addCriterion("STATUS_USED is null");
            return (Criteria) this;
        }

        public Criteria andStatusUsedIsNotNull() {
            addCriterion("STATUS_USED is not null");
            return (Criteria) this;
        }

        public Criteria andStatusUsedEqualTo(String value) {
            addCriterion("STATUS_USED =", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedNotEqualTo(String value) {
            addCriterion("STATUS_USED <>", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedGreaterThan(String value) {
            addCriterion("STATUS_USED >", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS_USED >=", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedLessThan(String value) {
            addCriterion("STATUS_USED <", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedLessThanOrEqualTo(String value) {
            addCriterion("STATUS_USED <=", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedLike(String value) {
            addCriterion("STATUS_USED like", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedNotLike(String value) {
            addCriterion("STATUS_USED not like", value, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedIn(List<String> values) {
            addCriterion("STATUS_USED in", values, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedNotIn(List<String> values) {
            addCriterion("STATUS_USED not in", values, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedBetween(String value1, String value2) {
            addCriterion("STATUS_USED between", value1, value2, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andStatusUsedNotBetween(String value1, String value2) {
            addCriterion("STATUS_USED not between", value1, value2, "statusUsed");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("LOGIN_ID is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("LOGIN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(String value) {
            addCriterion("LOGIN_ID =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(String value) {
            addCriterion("LOGIN_ID <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(String value) {
            addCriterion("LOGIN_ID >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_ID >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(String value) {
            addCriterion("LOGIN_ID <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_ID <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLike(String value) {
            addCriterion("LOGIN_ID like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotLike(String value) {
            addCriterion("LOGIN_ID not like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<String> values) {
            addCriterion("LOGIN_ID in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<String> values) {
            addCriterion("LOGIN_ID not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(String value1, String value2) {
            addCriterion("LOGIN_ID between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(String value1, String value2) {
            addCriterion("LOGIN_ID not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNull() {
            addCriterion("LOGIN_PWD is null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIsNotNull() {
            addCriterion("LOGIN_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdEqualTo(String value) {
            addCriterion("LOGIN_PWD =", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotEqualTo(String value) {
            addCriterion("LOGIN_PWD <>", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThan(String value) {
            addCriterion("LOGIN_PWD >", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_PWD >=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThan(String value) {
            addCriterion("LOGIN_PWD <", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_PWD <=", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdLike(String value) {
            addCriterion("LOGIN_PWD like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotLike(String value) {
            addCriterion("LOGIN_PWD not like", value, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdIn(List<String> values) {
            addCriterion("LOGIN_PWD in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotIn(List<String> values) {
            addCriterion("LOGIN_PWD not in", values, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdBetween(String value1, String value2) {
            addCriterion("LOGIN_PWD between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andLoginPwdNotBetween(String value1, String value2) {
            addCriterion("LOGIN_PWD not between", value1, value2, "loginPwd");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginIsNull() {
            addCriterion("IS_FIRST_LOGIN is null");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginIsNotNull() {
            addCriterion("IS_FIRST_LOGIN is not null");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginEqualTo(String value) {
            addCriterion("IS_FIRST_LOGIN =", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginNotEqualTo(String value) {
            addCriterion("IS_FIRST_LOGIN <>", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginGreaterThan(String value) {
            addCriterion("IS_FIRST_LOGIN >", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginGreaterThanOrEqualTo(String value) {
            addCriterion("IS_FIRST_LOGIN >=", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginLessThan(String value) {
            addCriterion("IS_FIRST_LOGIN <", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginLessThanOrEqualTo(String value) {
            addCriterion("IS_FIRST_LOGIN <=", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginLike(String value) {
            addCriterion("IS_FIRST_LOGIN like", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginNotLike(String value) {
            addCriterion("IS_FIRST_LOGIN not like", value, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginIn(List<String> values) {
            addCriterion("IS_FIRST_LOGIN in", values, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginNotIn(List<String> values) {
            addCriterion("IS_FIRST_LOGIN not in", values, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginBetween(String value1, String value2) {
            addCriterion("IS_FIRST_LOGIN between", value1, value2, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginNotBetween(String value1, String value2) {
            addCriterion("IS_FIRST_LOGIN not between", value1, value2, "isFirstLogin");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyIsNull() {
            addCriterion("IS_FORCE_MODIFY is null");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyIsNotNull() {
            addCriterion("IS_FORCE_MODIFY is not null");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyEqualTo(String value) {
            addCriterion("IS_FORCE_MODIFY =", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyNotEqualTo(String value) {
            addCriterion("IS_FORCE_MODIFY <>", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyGreaterThan(String value) {
            addCriterion("IS_FORCE_MODIFY >", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyGreaterThanOrEqualTo(String value) {
            addCriterion("IS_FORCE_MODIFY >=", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyLessThan(String value) {
            addCriterion("IS_FORCE_MODIFY <", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyLessThanOrEqualTo(String value) {
            addCriterion("IS_FORCE_MODIFY <=", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyLike(String value) {
            addCriterion("IS_FORCE_MODIFY like", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyNotLike(String value) {
            addCriterion("IS_FORCE_MODIFY not like", value, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyIn(List<String> values) {
            addCriterion("IS_FORCE_MODIFY in", values, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyNotIn(List<String> values) {
            addCriterion("IS_FORCE_MODIFY not in", values, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyBetween(String value1, String value2) {
            addCriterion("IS_FORCE_MODIFY between", value1, value2, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsForceModifyNotBetween(String value1, String value2) {
            addCriterion("IS_FORCE_MODIFY not between", value1, value2, "isForceModify");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetIsNull() {
            addCriterion("IS_PWD_RESET is null");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetIsNotNull() {
            addCriterion("IS_PWD_RESET is not null");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetEqualTo(String value) {
            addCriterion("IS_PWD_RESET =", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetNotEqualTo(String value) {
            addCriterion("IS_PWD_RESET <>", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetGreaterThan(String value) {
            addCriterion("IS_PWD_RESET >", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetGreaterThanOrEqualTo(String value) {
            addCriterion("IS_PWD_RESET >=", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetLessThan(String value) {
            addCriterion("IS_PWD_RESET <", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetLessThanOrEqualTo(String value) {
            addCriterion("IS_PWD_RESET <=", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetLike(String value) {
            addCriterion("IS_PWD_RESET like", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetNotLike(String value) {
            addCriterion("IS_PWD_RESET not like", value, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetIn(List<String> values) {
            addCriterion("IS_PWD_RESET in", values, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetNotIn(List<String> values) {
            addCriterion("IS_PWD_RESET not in", values, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetBetween(String value1, String value2) {
            addCriterion("IS_PWD_RESET between", value1, value2, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsPwdResetNotBetween(String value1, String value2) {
            addCriterion("IS_PWD_RESET not between", value1, value2, "isPwdReset");
            return (Criteria) this;
        }

        public Criteria andIsBlockIsNull() {
            addCriterion("IS_BLOCK is null");
            return (Criteria) this;
        }

        public Criteria andIsBlockIsNotNull() {
            addCriterion("IS_BLOCK is not null");
            return (Criteria) this;
        }

        public Criteria andIsBlockEqualTo(String value) {
            addCriterion("IS_BLOCK =", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockNotEqualTo(String value) {
            addCriterion("IS_BLOCK <>", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockGreaterThan(String value) {
            addCriterion("IS_BLOCK >", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockGreaterThanOrEqualTo(String value) {
            addCriterion("IS_BLOCK >=", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockLessThan(String value) {
            addCriterion("IS_BLOCK <", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockLessThanOrEqualTo(String value) {
            addCriterion("IS_BLOCK <=", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockLike(String value) {
            addCriterion("IS_BLOCK like", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockNotLike(String value) {
            addCriterion("IS_BLOCK not like", value, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockIn(List<String> values) {
            addCriterion("IS_BLOCK in", values, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockNotIn(List<String> values) {
            addCriterion("IS_BLOCK not in", values, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockBetween(String value1, String value2) {
            addCriterion("IS_BLOCK between", value1, value2, "isBlock");
            return (Criteria) this;
        }

        public Criteria andIsBlockNotBetween(String value1, String value2) {
            addCriterion("IS_BLOCK not between", value1, value2, "isBlock");
            return (Criteria) this;
        }

        public Criteria andBlockDateIsNull() {
            addCriterion("BLOCK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBlockDateIsNotNull() {
            addCriterion("BLOCK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBlockDateEqualTo(String value) {
            addCriterion("BLOCK_DATE =", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateNotEqualTo(String value) {
            addCriterion("BLOCK_DATE <>", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateGreaterThan(String value) {
            addCriterion("BLOCK_DATE >", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_DATE >=", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateLessThan(String value) {
            addCriterion("BLOCK_DATE <", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_DATE <=", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateLike(String value) {
            addCriterion("BLOCK_DATE like", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateNotLike(String value) {
            addCriterion("BLOCK_DATE not like", value, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateIn(List<String> values) {
            addCriterion("BLOCK_DATE in", values, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateNotIn(List<String> values) {
            addCriterion("BLOCK_DATE not in", values, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateBetween(String value1, String value2) {
            addCriterion("BLOCK_DATE between", value1, value2, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockDateNotBetween(String value1, String value2) {
            addCriterion("BLOCK_DATE not between", value1, value2, "blockDate");
            return (Criteria) this;
        }

        public Criteria andBlockTypeIsNull() {
            addCriterion("BLOCK_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBlockTypeIsNotNull() {
            addCriterion("BLOCK_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBlockTypeEqualTo(String value) {
            addCriterion("BLOCK_TYPE =", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeNotEqualTo(String value) {
            addCriterion("BLOCK_TYPE <>", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeGreaterThan(String value) {
            addCriterion("BLOCK_TYPE >", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_TYPE >=", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeLessThan(String value) {
            addCriterion("BLOCK_TYPE <", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_TYPE <=", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeLike(String value) {
            addCriterion("BLOCK_TYPE like", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeNotLike(String value) {
            addCriterion("BLOCK_TYPE not like", value, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeIn(List<String> values) {
            addCriterion("BLOCK_TYPE in", values, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeNotIn(List<String> values) {
            addCriterion("BLOCK_TYPE not in", values, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeBetween(String value1, String value2) {
            addCriterion("BLOCK_TYPE between", value1, value2, "blockType");
            return (Criteria) this;
        }

        public Criteria andBlockTypeNotBetween(String value1, String value2) {
            addCriterion("BLOCK_TYPE not between", value1, value2, "blockType");
            return (Criteria) this;
        }

        public Criteria andIsRevisableIsNull() {
            addCriterion("IS_REVISABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsRevisableIsNotNull() {
            addCriterion("IS_REVISABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsRevisableEqualTo(String value) {
            addCriterion("IS_REVISABLE =", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableNotEqualTo(String value) {
            addCriterion("IS_REVISABLE <>", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableGreaterThan(String value) {
            addCriterion("IS_REVISABLE >", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_REVISABLE >=", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableLessThan(String value) {
            addCriterion("IS_REVISABLE <", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableLessThanOrEqualTo(String value) {
            addCriterion("IS_REVISABLE <=", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableLike(String value) {
            addCriterion("IS_REVISABLE like", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableNotLike(String value) {
            addCriterion("IS_REVISABLE not like", value, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableIn(List<String> values) {
            addCriterion("IS_REVISABLE in", values, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableNotIn(List<String> values) {
            addCriterion("IS_REVISABLE not in", values, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableBetween(String value1, String value2) {
            addCriterion("IS_REVISABLE between", value1, value2, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsRevisableNotBetween(String value1, String value2) {
            addCriterion("IS_REVISABLE not between", value1, value2, "isRevisable");
            return (Criteria) this;
        }

        public Criteria andIsErasableIsNull() {
            addCriterion("IS_ERASABLE is null");
            return (Criteria) this;
        }

        public Criteria andIsErasableIsNotNull() {
            addCriterion("IS_ERASABLE is not null");
            return (Criteria) this;
        }

        public Criteria andIsErasableEqualTo(String value) {
            addCriterion("IS_ERASABLE =", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableNotEqualTo(String value) {
            addCriterion("IS_ERASABLE <>", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableGreaterThan(String value) {
            addCriterion("IS_ERASABLE >", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ERASABLE >=", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableLessThan(String value) {
            addCriterion("IS_ERASABLE <", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableLessThanOrEqualTo(String value) {
            addCriterion("IS_ERASABLE <=", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableLike(String value) {
            addCriterion("IS_ERASABLE like", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableNotLike(String value) {
            addCriterion("IS_ERASABLE not like", value, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableIn(List<String> values) {
            addCriterion("IS_ERASABLE in", values, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableNotIn(List<String> values) {
            addCriterion("IS_ERASABLE not in", values, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableBetween(String value1, String value2) {
            addCriterion("IS_ERASABLE between", value1, value2, "isErasable");
            return (Criteria) this;
        }

        public Criteria andIsErasableNotBetween(String value1, String value2) {
            addCriterion("IS_ERASABLE not between", value1, value2, "isErasable");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("LAST_LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("LAST_LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("LAST_LOGIN_TIME >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("LAST_LOGIN_TIME <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("LAST_LOGIN_TIME in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("LAST_LOGIN_TIME not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_LOGIN_TIME between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_LOGIN_TIME not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateIsNull() {
            addCriterion("RESET_PWD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateIsNotNull() {
            addCriterion("RESET_PWD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateEqualTo(String value) {
            addCriterion("RESET_PWD_DATE =", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateNotEqualTo(String value) {
            addCriterion("RESET_PWD_DATE <>", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateGreaterThan(String value) {
            addCriterion("RESET_PWD_DATE >", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateGreaterThanOrEqualTo(String value) {
            addCriterion("RESET_PWD_DATE >=", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateLessThan(String value) {
            addCriterion("RESET_PWD_DATE <", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateLessThanOrEqualTo(String value) {
            addCriterion("RESET_PWD_DATE <=", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateLike(String value) {
            addCriterion("RESET_PWD_DATE like", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateNotLike(String value) {
            addCriterion("RESET_PWD_DATE not like", value, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateIn(List<String> values) {
            addCriterion("RESET_PWD_DATE in", values, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateNotIn(List<String> values) {
            addCriterion("RESET_PWD_DATE not in", values, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateBetween(String value1, String value2) {
            addCriterion("RESET_PWD_DATE between", value1, value2, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andResetPwdDateNotBetween(String value1, String value2) {
            addCriterion("RESET_PWD_DATE not between", value1, value2, "resetPwdDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedIsNull() {
            addCriterion("FLAG_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedIsNotNull() {
            addCriterion("FLAG_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedEqualTo(String value) {
            addCriterion("FLAG_DELETED =", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedNotEqualTo(String value) {
            addCriterion("FLAG_DELETED <>", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedGreaterThan(String value) {
            addCriterion("FLAG_DELETED >", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("FLAG_DELETED >=", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedLessThan(String value) {
            addCriterion("FLAG_DELETED <", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedLessThanOrEqualTo(String value) {
            addCriterion("FLAG_DELETED <=", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedLike(String value) {
            addCriterion("FLAG_DELETED like", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedNotLike(String value) {
            addCriterion("FLAG_DELETED not like", value, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedIn(List<String> values) {
            addCriterion("FLAG_DELETED in", values, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedNotIn(List<String> values) {
            addCriterion("FLAG_DELETED not in", values, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedBetween(String value1, String value2) {
            addCriterion("FLAG_DELETED between", value1, value2, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andFlagDeletedNotBetween(String value1, String value2) {
            addCriterion("FLAG_DELETED not between", value1, value2, "flagDeleted");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(String value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(String value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(String value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(String value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLike(String value) {
            addCriterion("LAST_UPD_BY like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotLike(String value) {
            addCriterion("LAST_UPD_BY not like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<String> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<String> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeIsNull() {
            addCriterion("LAST_UPD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeIsNotNull() {
            addCriterion("LAST_UPD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeEqualTo(Date value) {
            addCriterion("LAST_UPD_TIME =", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotEqualTo(Date value) {
            addCriterion("LAST_UPD_TIME <>", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeGreaterThan(Date value) {
            addCriterion("LAST_UPD_TIME >", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_TIME >=", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeLessThan(Date value) {
            addCriterion("LAST_UPD_TIME <", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPD_TIME <=", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeIn(List<Date> values) {
            addCriterion("LAST_UPD_TIME in", values, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotIn(List<Date> values) {
            addCriterion("LAST_UPD_TIME not in", values, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_TIME between", value1, value2, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPD_TIME not between", value1, value2, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLoginNumIsNull() {
            addCriterion("LOGIN_NUM is null");
            return (Criteria) this;
        }

        public Criteria andLoginNumIsNotNull() {
            addCriterion("LOGIN_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNumEqualTo(String value) {
            addCriterion("LOGIN_NUM =", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumNotEqualTo(String value) {
            addCriterion("LOGIN_NUM <>", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumGreaterThan(String value) {
            addCriterion("LOGIN_NUM >", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_NUM >=", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumLessThan(String value) {
            addCriterion("LOGIN_NUM <", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_NUM <=", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumLike(String value) {
            addCriterion("LOGIN_NUM like", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumNotLike(String value) {
            addCriterion("LOGIN_NUM not like", value, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumIn(List<String> values) {
            addCriterion("LOGIN_NUM in", values, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumNotIn(List<String> values) {
            addCriterion("LOGIN_NUM not in", values, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumBetween(String value1, String value2) {
            addCriterion("LOGIN_NUM between", value1, value2, "loginNum");
            return (Criteria) this;
        }

        public Criteria andLoginNumNotBetween(String value1, String value2) {
            addCriterion("LOGIN_NUM not between", value1, value2, "loginNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 02 22:53:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}