package com.self.entity;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ENTITY_OID
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private BigDecimal entityOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DISPLAY_NAME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.GENDER
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MOBILE_NO
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TEL_NO
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATUS_USED
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String statusUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGIN_ID
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGIN_PWD
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IS_FIRST_LOGIN
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String isFirstLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IS_FORCE_MODIFY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String isForceModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IS_PWD_RESET
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String isPwdReset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IS_BLOCK
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String isBlock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.BLOCK_DATE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String blockDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.BLOCK_TYPE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String blockType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IS_REVISABLE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String isRevisable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IS_ERASABLE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String isErasable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_LOGIN_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.RESET_PWD_DATE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String resetPwdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REMARK
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.VERSION
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.FLAG_DELETED
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String flagDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATED_BY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATED_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_UPD_BY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String lastUpdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_UPD_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private Date lastUpdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOGIN_NUM
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    private String loginNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ENTITY_OID
     *
     * @return the value of user.ENTITY_OID
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public BigDecimal getEntityOid() {
        return entityOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ENTITY_OID
     *
     * @param entityOid the value for user.ENTITY_OID
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setEntityOid(BigDecimal entityOid) {
        this.entityOid = entityOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DISPLAY_NAME
     *
     * @return the value of user.DISPLAY_NAME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DISPLAY_NAME
     *
     * @param displayName the value for user.DISPLAY_NAME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.GENDER
     *
     * @return the value of user.GENDER
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.GENDER
     *
     * @param gender the value for user.GENDER
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MOBILE_NO
     *
     * @return the value of user.MOBILE_NO
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MOBILE_NO
     *
     * @param mobileNo the value for user.MOBILE_NO
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TEL_NO
     *
     * @return the value of user.TEL_NO
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TEL_NO
     *
     * @param telNo the value for user.TEL_NO
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATUS_USED
     *
     * @return the value of user.STATUS_USED
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getStatusUsed() {
        return statusUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATUS_USED
     *
     * @param statusUsed the value for user.STATUS_USED
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setStatusUsed(String statusUsed) {
        this.statusUsed = statusUsed == null ? null : statusUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGIN_ID
     *
     * @return the value of user.LOGIN_ID
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGIN_ID
     *
     * @param loginId the value for user.LOGIN_ID
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGIN_PWD
     *
     * @return the value of user.LOGIN_PWD
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGIN_PWD
     *
     * @param loginPwd the value for user.LOGIN_PWD
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IS_FIRST_LOGIN
     *
     * @return the value of user.IS_FIRST_LOGIN
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getIsFirstLogin() {
        return isFirstLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IS_FIRST_LOGIN
     *
     * @param isFirstLogin the value for user.IS_FIRST_LOGIN
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setIsFirstLogin(String isFirstLogin) {
        this.isFirstLogin = isFirstLogin == null ? null : isFirstLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IS_FORCE_MODIFY
     *
     * @return the value of user.IS_FORCE_MODIFY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getIsForceModify() {
        return isForceModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IS_FORCE_MODIFY
     *
     * @param isForceModify the value for user.IS_FORCE_MODIFY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setIsForceModify(String isForceModify) {
        this.isForceModify = isForceModify == null ? null : isForceModify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IS_PWD_RESET
     *
     * @return the value of user.IS_PWD_RESET
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getIsPwdReset() {
        return isPwdReset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IS_PWD_RESET
     *
     * @param isPwdReset the value for user.IS_PWD_RESET
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setIsPwdReset(String isPwdReset) {
        this.isPwdReset = isPwdReset == null ? null : isPwdReset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IS_BLOCK
     *
     * @return the value of user.IS_BLOCK
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getIsBlock() {
        return isBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IS_BLOCK
     *
     * @param isBlock the value for user.IS_BLOCK
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setIsBlock(String isBlock) {
        this.isBlock = isBlock == null ? null : isBlock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.BLOCK_DATE
     *
     * @return the value of user.BLOCK_DATE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getBlockDate() {
        return blockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.BLOCK_DATE
     *
     * @param blockDate the value for user.BLOCK_DATE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setBlockDate(String blockDate) {
        this.blockDate = blockDate == null ? null : blockDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.BLOCK_TYPE
     *
     * @return the value of user.BLOCK_TYPE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getBlockType() {
        return blockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.BLOCK_TYPE
     *
     * @param blockType the value for user.BLOCK_TYPE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setBlockType(String blockType) {
        this.blockType = blockType == null ? null : blockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IS_REVISABLE
     *
     * @return the value of user.IS_REVISABLE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getIsRevisable() {
        return isRevisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IS_REVISABLE
     *
     * @param isRevisable the value for user.IS_REVISABLE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setIsRevisable(String isRevisable) {
        this.isRevisable = isRevisable == null ? null : isRevisable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IS_ERASABLE
     *
     * @return the value of user.IS_ERASABLE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getIsErasable() {
        return isErasable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IS_ERASABLE
     *
     * @param isErasable the value for user.IS_ERASABLE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setIsErasable(String isErasable) {
        this.isErasable = isErasable == null ? null : isErasable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_LOGIN_TIME
     *
     * @return the value of user.LAST_LOGIN_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for user.LAST_LOGIN_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.RESET_PWD_DATE
     *
     * @return the value of user.RESET_PWD_DATE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getResetPwdDate() {
        return resetPwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.RESET_PWD_DATE
     *
     * @param resetPwdDate the value for user.RESET_PWD_DATE
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setResetPwdDate(String resetPwdDate) {
        this.resetPwdDate = resetPwdDate == null ? null : resetPwdDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REMARK
     *
     * @return the value of user.REMARK
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REMARK
     *
     * @param remark the value for user.REMARK
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.VERSION
     *
     * @return the value of user.VERSION
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.VERSION
     *
     * @param version the value for user.VERSION
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.FLAG_DELETED
     *
     * @return the value of user.FLAG_DELETED
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getFlagDeleted() {
        return flagDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.FLAG_DELETED
     *
     * @param flagDeleted the value for user.FLAG_DELETED
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setFlagDeleted(String flagDeleted) {
        this.flagDeleted = flagDeleted == null ? null : flagDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATED_BY
     *
     * @return the value of user.CREATED_BY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATED_BY
     *
     * @param createdBy the value for user.CREATED_BY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATED_TIME
     *
     * @return the value of user.CREATED_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATED_TIME
     *
     * @param createdTime the value for user.CREATED_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_UPD_BY
     *
     * @return the value of user.LAST_UPD_BY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_UPD_BY
     *
     * @param lastUpdBy the value for user.LAST_UPD_BY
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_UPD_TIME
     *
     * @return the value of user.LAST_UPD_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public Date getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for user.LAST_UPD_TIME
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setLastUpdTime(Date lastUpdTime) {
        this.lastUpdTime = lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOGIN_NUM
     *
     * @return the value of user.LOGIN_NUM
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public String getLoginNum() {
        return loginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOGIN_NUM
     *
     * @param loginNum the value for user.LOGIN_NUM
     *
     * @mbg.generated Fri Mar 02 22:53:43 CST 2018
     */
    public void setLoginNum(String loginNum) {
        this.loginNum = loginNum == null ? null : loginNum.trim();
    }
}